import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#fff5f0',
    paddingHorizontal: 20,
    paddingVertical: 50,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 20,
    zIndex: 10,
  },
  backBtn: {
    backgroundColor: 'white',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    height: 40,
    width: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageTitle: {
    fontSize: 20,
    fontFamily: 'Poppins-Bold',
    color: '#1a1a1a',
  },
  likeButton: {
    height: 40,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    borderRadius: 20,
  },
  scrollViewStyle: {
    paddingBottom: 160,
  },
  cartCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    marginBottom: 16,
    padding: 12,
    height: 110,
    borderWidth: 1,
    borderColor: '#ffe3d9',
    elevation: 2,
    shadowColor: '#ff5b27',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    position: 'relative',
  },
  productImageContainer: {
    height: 86,
    width: 86,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    backgroundColor: '#fff5f0',
  },
  productImage: {
    width: '90%',
    height: '90%',
    borderRadius: 8,
    resizeMode: 'contain',
  },
  productInfo: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'space-between',
    height: '100%',
    paddingVertical: 2,
  },
  productName: {
    fontSize: 14,
    fontFamily: 'Poppins-Bold',
    color: '#1a1a1a',
    paddingRight: 32,
  },
  productPrice: {
    fontSize: 14,
    color: '#ff5b27',
    fontFamily: 'Poppins-Bold',
    marginTop: 2,
  },
  qtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff5f0',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ffe3d9',
    alignSelf: 'flex-start',
    paddingHorizontal: 4,
    paddingVertical: 2,
    marginTop: 4,
  },
  qtyBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyText: {
    fontSize: 14,
    fontFamily: 'Poppins-Bold',
    color: '#ff5b27',
    marginBottom: -2,
  },
  qtyValue: {
    marginHorizontal: 12,
    fontSize: 13,
    fontFamily: 'Poppins-Bold',
    color: '#1a1a1a',
  },
  cardTrashBtn: {
    position: 'absolute',
    top: 12,
    right: 12,
    padding: 4,
  },
  deleteAnimation: {
    backgroundColor: '#ffe8e8',
    justifyContent: 'center',
    alignItems: 'center',
    width: 80,
    borderRadius: 16,
    height: 110,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#ffd0d0',
  },
  emptyCartContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 60,
    paddingHorizontal: 20,
  },
  emptyIconWrapper: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#ffe7dd',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#ff5b27',
  },
  emptyCartText: {
    fontSize: 18,
    fontFamily: 'Poppins-Bold',
    color: '#1a1a1a',
    marginBottom: 8,
  },
  emptyCartSubtext: {
    fontSize: 13,
    fontFamily: 'Poppins-Regular',
    color: '#777',
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 24,
  },
  startShoppingBtn: {
    backgroundColor: '#ff5b27',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 24,
    elevation: 2,
    shadowColor: '#ff5b27',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  startShoppingText: {
    color: '#fff',
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
    marginBottom: -2,
  },
  summaryCard: {
    marginTop: 20,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#ffe3d9',
    elevation: 2,
    shadowColor: '#ff5b27',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 6,
  },
  label: {
    fontSize: 13,
    fontFamily: 'Poppins-Regular',
    color: '#666',
  },
  value: {
    fontSize: 13,
    fontFamily: 'Poppins-Bold',
    color: '#1a1a1a',
  },
  divider: {
    height: 1,
    backgroundColor: '#ffe3d9',
    marginVertical: 12,
  },
  totalLabel: {
    fontSize: 15,
    fontFamily: 'Poppins-Bold',
    color: '#1a1a1a',
  },
  totalValue: {
    fontSize: 18,
    fontFamily: 'Poppins-Bold',
    color: '#ff5b27',
  },
  checkoutBtn: {
    backgroundColor: '#ff5b27',
    marginTop: 16,
    height: 50,
    borderRadius: 25,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    elevation: 3,
    shadowColor: '#ff5b27',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
  },
  checkoutText: {
    color: '#fff',
    fontSize: 15,
    fontFamily: 'Poppins-Bold',
    marginBottom: -2,
  },
});

export default styles;
