import { StyleSheet } from 'react-native';
import theme from '../../theme/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff5f0',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 60,
    paddingBottom: 20,
    paddingHorizontal: 20,
    zIndex: 10,
  },
  backBtn: {
    backgroundColor: 'white',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    height: 40,
    width: 40,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageTitle: {
    fontSize: 20,
    fontFamily: 'Poppins-Bold',
  },
  likeButton: {
    height: 40,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    borderRadius: 30,
  },
  scrollView: {
    paddingBottom: 160,
    paddingHorizontal: 20,
  },
  productMainContainer: {
    margin: 0,
  },
  productImgContainer: {
    width: '100%',
    height: 400,
    resizeMode: 'center',
    borderRadius: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ffe3d9',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  productImg: {
    width: '80%',
    height: '80%',
    borderRadius: 20,
    zIndex: 1000,
  },
  offerContainer: {
    backgroundColor: '#fff5f0',
    position: 'absolute',
    bottom: -20,
    right: 26,
    padding: 4,
    borderRadius: 30,
  },
  offer: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 30,
    backgroundColor: '#ff5b27',
  },
  offerText: {
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    marginBottom: -3,
    color: '#fff',
  },
  productContentContainer: {
    marginTop: 40,
    flexDirection: 'column',
  },
  productCategory: {
    color: '#000000a3',
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
  },
  productName: {
    fontSize: 20,
    fontFamily: 'Poppins-Bold',
    marginBottom: 10,
  },
  descritpionText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    marginBottom: 20,
  },
  productSubContentContainer: {
    flexDirection: 'column',
    marginBottom: 10,
  },
  labelContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  label: {
    fontFamily: 'Poppins-Medium',
    color: '#000000a3',
    fontSize: 14,
    marginBottom: -4,
  },
  priceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  priceSubContainer: {
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  offerPrice: {
    fontSize: 24,
    fontFamily: 'Poppins-Bold',
    margin: 0,
    padding: 0,
    color: '#ff5b27',
  },
  price: {
    textDecorationLine: 'line-through',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: '#000000a3',
  },
  rating: {
    fontSize: 14,
    color: '#ff5b27',
    fontFamily: 'Poppins-Medium',
    marginTop: 10,
  },
  modal: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  drawer: {
    backgroundColor: '#fff',
    paddingVertical: 26,
    paddingHorizontal: 18,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    height: 800,
  },
  modalScrollView: {
    paddingBottom: 100,
    flexDirection: 'column',
    gap: 24
  },
  imageUploadCard: {
    backgroundColor: '#FFF5F0',
    paddingVertical: 20,
    paddingHorizontal: 10,
    borderRadius: theme.BORDER_RADIUS.inputField,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ffe3d9',
  },
  previewImage: {
    width: '100%',
    height: 120,
    borderRadius: 12,
  },
  iconContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    width: 50,
    backgroundColor: '#ffe3d9',
    padding: 12,
    borderRadius: 100,
  },
  cardTitle: {
    fontSize: 14,
    fontFamily: 'Poppins-Medium',
    marginTop: 16,
    color: '#ff5b27',
  },
  cardSubTitle: {
    fontSize: 12,
    color: '#000000a3',
    textAlign: 'center',
    marginTop: -2,
    fontFamily: 'Poppins-Regular',
  },
  inputContainer: {
    flexDirection: 'column',
    gap: 6,
  },
  inputLabel: {
    fontSize: 14,
    color: '#000',
    fontFamily: 'Poppins-Medium',
  },
  inputSubContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    borderWidth: 1,
    borderColor: '#bbb',
    borderRadius: theme.BORDER_RADIUS.inputField,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  icon: {
    marginRight: 10,
  },
  input: {
    fontFamily: 'Poppins-Regular',
    color: '#000',
    marginBottom: -4
  },
  categoryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  categoryBtn: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: theme.BORDER_RADIUS.categoryBtn,
    borderWidth: 1,
    borderColor: '#00000061',
  },
  categoryBtnActive: {
    backgroundColor: '#ff5b27',
    borderColor: '#ff5b27',
  },
  categoryText: {
    fontSize: 13,
    fontFamily: 'Poppins-Regular',
    color: '#000',
  },
  categoryTextActive: {
    color: '#fff',
  },
  textAreaContainer: {
    height: 120,
    alignItems: 'flex-start',
    borderWidth: 1,
    borderColor: '#bbb',
    borderRadius: theme.BORDER_RADIUS.inputField,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  textArea: {
    flex: 1,
    fontFamily: 'Poppins-Regular',
    color: '#000',
  },
  button: {
    height: 60,
    backgroundColor: '#ff5b27',
    borderRadius: theme.BORDER_RADIUS.inputField,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontFamily: 'Poppins-Medium',
  },
});

export default styles;
