import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#fff5f0',
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 50,
    paddingBottom: 20,
    zIndex: 10,
  },
  backBtn: {
    borderColor: '#ffe3d9',
    borderWidth: 1,
    height: 40,
    width: 40,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageTitle: {
    fontSize: 20,
    fontFamily: 'Poppins-Bold',
  },
  searchBtn: {
    borderColor: '#ffe3d9',
    borderWidth: 1,
    height: 40,
    width: 40,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },

  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ffe3d9',
    borderRadius: 50,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginBottom: 20,
  },
  searchText: {
    fontFamily: 'Poppins-Regular',
    color: '#000',
  },

  cardHeaderTitle: {
    fontSize: 14,
    color: '#000',
    fontFamily: 'Poppins-SemiBold',
    marginBottom: 5,
  },
  cardContainer: {
    backgroundColor: '#fff',
    flexDirection: 'column',
    justifyContent: 'space-between',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    borderRadius: 16,
    marginBottom: 16,
  },
  CardSubContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: 'column',
    gap: 20,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  rowText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: '#000',
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 6,
    padding: 3,
    backgroundColor: '#ffe7dd',
    borderWidth: 1,
    borderColor: '#ff5b27',
    alignItems: 'center',
    justifyContent: 'center',
  },
  line: {
    height: 1,
    width: '100%',
    backgroundColor: '#ffe3d9',

    marginTop: 20,
  },
  scrollView: {
    paddingBottom: 100,
  },
  faqListContainer: {
    marginTop: 10,
    paddingLeft: 10,
    backgroundColor: '#fffaf8',
    borderRadius: 8,
    padding: 8,
  },
  faqItem: {
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#fcf0ea',
    paddingBottom: 8,
  },
  faqQuestionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  faqQuestionText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 13,
    color: '#333',
    flex: 1,
    marginRight: 10,
  },
  faqAnswerText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    color: '#666',
    marginTop: 4,
    lineHeight: 18,
  },
  // Chat Modal Styles
  modalContainer: {
    flex: 1,
    backgroundColor: '#fff5f0',
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ff5b27',
    paddingTop: 50,
    paddingBottom: 15,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3.84,
  },
  chatHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  chatTitleContainer: {
    flexDirection: 'column',
  },
  chatTitle: {
    fontFamily: 'Poppins-Bold',
    fontSize: 16,
    color: '#fff',
  },
  chatSubtitle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    color: '#ffe3d9',
  },
  chatCloseBtn: {
    padding: 4,
  },
  chatMessageList: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  chatMessageListContent: {
    paddingBottom: 20,
  },
  messageBubble: {
    maxWidth: '80%',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    marginBottom: 10,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
  },
  userMessageBubble: {
    alignSelf: 'flex-end',
    backgroundColor: '#ff5b27',
    borderBottomRightRadius: 2,
  },
  botMessageBubble: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    borderBottomLeftRadius: 2,
  },
  messageText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    lineHeight: 18,
  },
  userMessageText: {
    color: '#fff',
  },
  botMessageText: {
    color: '#333',
  },
  messageTime: {
    fontFamily: 'Poppins-Regular',
    fontSize: 9,
    alignSelf: 'flex-end',
    marginTop: 4,
  },
  userMessageTime: {
    color: '#ffdcd0',
  },
  botMessageTime: {
    color: '#999',
  },
  typingIndicatorContainer: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    borderBottomLeftRadius: 2,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  typingText: {
    fontFamily: 'Poppins-Italic',
    fontSize: 12,
    color: '#888',
  },
  quickRepliesContainer: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: '#ffe3d9',
    backgroundColor: '#fff5f0',
  },
  quickRepliesLabel: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 11,
    color: '#ff5b27',
    marginBottom: 6,
  },
  quickRepliesScroll: {
    flexDirection: 'row',
    gap: 8,
  },
  quickReplyChip: {
    backgroundColor: '#ffe7dd',
    borderColor: '#ff5b27',
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
  },
  quickReplyChipText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: '#ff5b27',
  },
  chatInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#ffe3d9',
    gap: 10,
  },
  chatInput: {
    flex: 1,
    backgroundColor: '#fff5f0',
    borderWidth: 1,
    borderColor: '#ffe3d9',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 8,
    color: '#000',
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    maxHeight: 100,
  },
  chatSendBtn: {
    backgroundColor: '#ff5b27',
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Search Results
  searchResultsContainer: {
    flex: 1,
  },
  searchResultsTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    color: '#ff5b27',
    marginBottom: 10,
  },
  searchResultCard: {
    backgroundColor: '#fff',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  searchResultCatText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 10,
    color: '#ff5b27',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
});

export default styles;
