import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF5F0',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 60,
    paddingBottom: 20,
    paddingHorizontal: 20,
    zIndex: 10,
  },
  backBtn: {
    backgroundColor: 'white',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    height: 40,
    width: 40,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageTitle: {
    fontSize: 20,
    fontFamily: 'Poppins-Bold',
  },
  searchBtn: {
    backgroundColor: 'white',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    height: 40,
    width: 40,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ffe3d9',
    borderRadius: 50,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  searchText: {
    fontFamily: 'Poppins-Regular',
    color: '#000',
    marginBottom: -4,
  },
  scrollContent: {
    paddingBottom: 200,
  },
  subContainer: {
    paddingHorizontal: 20,
  },
  storeBanner: {
    height: 280,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#ffe3d9',
    backgroundColor: '#fff',
    marginBottom: 20,
    position: 'relative',
  },
  storeImgContainer: {
    height: '60%',
    width: 'auto',
  },
  storeImg: {
    height: '100%',
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
  },
  storeContentContainer: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'column',
    borderRadius: 20,
    gap: 6,
    backgroundColor: '#fff',
  },
  storeContentSubContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  storeName: {
    fontSize: 20,
    fontFamily: 'Poppins-Bold',
    color: '#ff6a32',
  },
  storeCategory: {
    backgroundColor: '#ff6a32',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  storeCatgoryText: {
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    color: '#fff',
    marginBottom: -1,
  },
  storeAddressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  storeLocationIcon: {
    marginLeft: -2,
    marginTop: -4,
  },
  storeAddress: {
    fontSize: 12,
    fontFamily: 'Poppins-Regular',
  },
  categoryContainer: {
    paddingBottom: 20,
    marginLeft: 20,
  },
  categoryBtn: {
    paddingHorizontal: 30,
    paddingVertical: 12,
    backgroundColor: '#ffffff',
    borderRadius: 30,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#ffe3d9',
  },
  categoryBtnActive: {
    backgroundColor: '#ff5b27',
    borderColor: '#ff5b27',
  },
  categoryText: {
    fontSize: 12,
    color: '#000000a3',
    fontFamily: 'Poppins-Regular',
  },
  categoryTextActive: {
    color: '#FFFFFF',
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 14,
    paddingHorizontal: 20,
  },
  productCard: {
    width: '48%',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: 10,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ffe3d9',
    borderRadius: 12,
    padding: 10,
    position: 'relative',
  },
  productImageContainer: {
    alignItems: 'center',
    borderRadius: 10,
  },
  productImage: {
    width: '100%',
    height: 168,
    resizeMode: 'cover',
    borderRadius: 10,
  },
  productContentContainer: {
    flexDirection: 'column',
  },
  productName: {
    fontSize: 14,
    fontFamily: 'Poppins-SemiBold',
    color: '#ff5b27',
  },
  productcategory: {
    fontSize: 10,
    fontFamily: 'Poppins-SemiBold',
    color: '#000000a3',
    marginTop: -2,
  },
  productSubContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  productPrice: {
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
    color: '#ff5b27',
  },
  stockBadge: {
    backgroundColor: '#dddddd',
    paddingVertical: 2,
    paddingHorizontal: 6,
    width: 80,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
    position: 'absolute',
    top: 10,
    left: 10,
  },
  stockText: {
    marginTop: 2,
    fontFamily: 'Poppins-Medium',
    fontSize: 10,
  },
  outOfStockStatus: {
    fontSize: 10,
    fontFamily: 'Poppins-Medium',
    color: '#ff0000',
  },
  lowStockStatus: {
    fontSize: 10,
    fontFamily: 'Poppins-Medium',
    color: '#fda500',
  },
  inStockStatus: {
    fontSize: 10,
    fontFamily: 'Poppins-Medium',
    color: '#277a00',
  },
});

export default styles;
