import { Dimensions, StyleSheet } from 'react-native';
import { responsive } from '../../theme/responsive';

const { width } = Dimensions.get('window');
const screenWidth = width;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff5f0',
    paddingHorizontal: 20,
    paddingVertical: 50,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 20,
    zIndex: 10,
  },
  backBtn: {
    backgroundColor: 'white',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    height: 40,
    width: 40,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageTitle: {
    fontSize: 20,
    fontFamily: 'Poppins-Bold',
  },
  likeButton: {
    height: 40,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    borderRadius: 30,
  },
  scrollView: {
    paddingBottom: 160,
  },
  productMainContainer: {
    margin: 0,
    padding: 0,
  },
  productImgContainer: {
    width: '100%',
    height: 360,
    resizeMode: 'contain',
    borderRadius: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ffe3d9',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
  },
  productImg: {
    width: '100%',
    height: '100%',
    borderRadius: 20,
    zIndex: 1000,
  },
  offerContainer: {
    backgroundColor: '#fff5f0',
    position: 'absolute',
    bottom: -20,
    right: 26,
    padding: 4,
    borderRadius: 30,
  },
  offer: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 30,
    backgroundColor: '#ff5b27',
  },
  offerText: {
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    marginBottom: -3,
    color: '#fff',
  },
  stockBadgeContainer: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#008000',
    position: 'absolute',
    top: 14,
    left: 14,
    zIndex: 999999,
  },
  stockBadgeText: {
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    marginBottom: -3,
    color: '#008000',
  },
  outOfStockBadgeContainer: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FF0000',
    position: 'absolute',
    top: 14,
    left: 14,
    zIndex: 999999,
  },
  outOfStockBadgeText: {
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    marginBottom: -3,
    color: '#FF0000',
  },
  productContentContainer: {
    marginTop: 20,
    flexDirection: 'column',
    gap: 10,
  },
  productSubContentContainer: {
    flexDirection: 'column',
    gap: 4,
  },
  productNameContainer: {
    flexDirection: 'column',
  },
  categoryText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: '#000000a3',
  },
  productName: {
    fontSize: 26,
    fontFamily: 'Poppins-Bold',
  },
  priceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  priceSubContainer: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  offerPriceText: {
    fontSize: 24,
    fontFamily: 'Poppins-Bold',
    margin: 0,
    padding: 0,
    color: '#ff5b27',
  },
  priceText: {
    textDecorationLine: 'line-through',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: '#000000a3',
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  ratingText: {
    marginBottom: -2,
    fontFamily: 'Poppins-Regular',
    color: '#000000a3',
  },
  descriptionContainer: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    fontFamily: 'Poppins-Bold',
  },
  descritpionText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: '#000000a3',
  },
  extraDetailContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ffe3d9',
    borderRadius: 10,
    marginBottom: 20,
    padding: 10,
  },
  infoContainer: {
    height: 100,
    width: '32%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoIcon: {
    marginBottom: 10,
  },
  infoTitle: {
    fontSize: 12,
    fontFamily: 'Poppins-Bold',
  },
  infoSubTitle: {
    fontSize: 12,
    fontFamily: 'Poppins-Regular',
    color: '#000000a3',
    marginTop: -4,
  },
  verticalLine: {
    borderRightWidth: 1,
    borderColor: '#ffe3d9',
  },
  shopSectionTitle: {
    fontSize: 16,
    fontFamily: 'Poppins-Bold',
    color: '#1a1a1a',
    marginTop: 16,
  },
  shopContainer: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ffe3d9',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 16,
    gap: 12,
    marginTop: 8,
    elevation: 2,
    shadowColor: '#ff5b27',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
  },
  shopImage: {
    width: 64,
    height: 64,
    borderRadius: 12,
    backgroundColor: '#f5f5f5',
  },
  shopContentContainer: {
    flex: 1,
    flexDirection: 'column',
  },
  shopCategoryText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 10,
    color: '#ff5b27',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  shopNameText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
    color: '#1a1a1a',
    marginBottom: 4,
  },
  shopRatingLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  shopRatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  shopRatingText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    color: '#666',
  },
  bulletSeparator: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#ccc',
    marginHorizontal: 8,
  },
  shopLocationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flex: 1,
  },
  shopLocationText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    color: '#666',
  },
  visitStoreBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#fff5f0',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ffe3d9',
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: width,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 28,
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderColor: '#ffe3d9',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
  },
  priceInfoContainer: {
    flexDirection: 'column',
  },
  priceLabel: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    color: '#888',
    marginBottom: -2,
  },
  priceValue: {
    fontFamily: 'Poppins-Bold',
    fontSize: 20,
    color: '#1a1a1a',
  },
  cartButton: {
    height: 48,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ff5b27',
    borderRadius: 24,
    paddingHorizontal: 24,
    gap: 8,
    elevation: 3,
    shadowColor: '#ff5b27',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
  },
  cartIcon: {
    marginRight: 2,
  },
  cartButtonText: {
    fontFamily: 'Poppins-Bold',
    color: '#fff',
    fontSize: 14,
    marginBottom: -2,
  },
});

export default styles;
