import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff5f0',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 60,
    paddingBottom: 20,
    paddingHorizontal: 20,
    zIndex: 10,
  },
  backBtn: {
    backgroundColor: 'white',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    height: 40,
    width: 40,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageTitle: {
    fontSize: 20,
    fontFamily: 'Poppins-Bold',
  },
  likeButton: {
    height: 40,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    borderRadius: 30,
  },
  scrollView: {
    paddingBottom: 160,
    paddingHorizontal: 20,
  },
  productMainContainer: {
    margin: 0,
    padding: 0,
  },
  productImgContainer: {
    width: '100%',
    height: 360,
    resizeMode: 'center',
    borderRadius: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ffe3d9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  productImg: {
    width: '80%',
    height: '80%',
    borderRadius: 20,
    zIndex: 1000,
  },
  offerContainer: {
    backgroundColor: '#fff5f0',
    position: 'absolute',
    bottom: -20,
    right: 26,
    padding: 4,
    borderRadius: 30,
  },
  offer: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 30,
    backgroundColor: '#ff5b27',
  },
  offerText: {
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    marginBottom: -3,
    color: '#fff',
  },
  stockBadgeContainer: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#008000',
    position: 'absolute',
    top: 14,
    left: 14,
    zIndex: 999999,
  },
  stockBadgeText: {
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    marginBottom: -3,
    color: '#008000',
  },
  outOfStockBadgeContainer: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FF0000',
    position: 'absolute',
    top: 14,
    left: 14,
    zIndex: 999999,
  },
  outOfStockBadgeText: {
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    marginBottom: -3,
    color: '#FF0000',
  },
  productContentContainer: {
    marginTop: 20,
    flexDirection: 'column',
    gap: 10,
  },
  productSubContentContainer: {
    flexDirection: 'column',
    gap: 4,
  },
  productNameContainer: {
    flexDirection: 'column',
  },
  categoryText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: '#000000a3',
  },
  productName: {
    fontSize: 26,
    fontFamily: 'Poppins-Bold',
  },
  priceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  priceSubContainer: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  offerPriceText: {
    fontSize: 24,
    fontFamily: 'Poppins-Bold',
    margin: 0,
    padding: 0,
    color: '#ff5b27',
  },
  priceText: {
    textDecorationLine: 'line-through',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: '#000000a3',
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  ratingText: {
    marginBottom: -2,
    fontFamily: 'Poppins-Regular',
    color: '#000000a3',
  },
  descriptionContainer: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    fontFamily: 'Poppins-Bold',
  },
  descritpionText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: '#000000a3',
  },
  extraDetailContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ffe3d9',
    borderRadius: 10,
    marginBottom: 20,
    padding: 10,
  },
  infoContainer: {
    height: 100,
    width: '32%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoIcon: {
    marginBottom: 10,
  },
  infoTitle: {
    fontSize: 12,
    fontFamily: 'Poppins-Bold',
  },
  infoSubTitle: {
    fontSize: 12,
    fontFamily: 'Poppins-Regular',
    color: '#000000a3',
    marginTop: -4,
  },
  verticalLine: {
    borderRightWidth: 1,
    borderColor: '#ffe3d9',
  },
  shopContainer: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ffe3d9',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 10,
    gap: 14,
  },
  shopImageContainer: {
    height: 90,
    width: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  shopImage: {
    width: '100%',
    height: '100%',
    borderRadius: 6,
  },
  shopContentContainer: {
    flexDirection: 'column',
  },
  shopNameText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 16,
    marginBottom: 4,
  },
  shopRatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  shopRatingText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: '#000000a3',
  },
  shopLocationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  shopLocationText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    marginBottom: -2,
    color: '#000000a3',
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: width,
    paddingHorizontal: 20,
    paddingTop: 20,
    marginBottom: 40,
    position: 'absolute',
    bottom: 0,
  },
  cartButton: {
    height: 60,
    width: '100%',
    backgroundColor: '#ff5b27',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
  },
  cartButtonText: {
    fontFamily: 'Poppins-Medium',
    color: '#fff',
    marginBottom: -2,
  },
});

export default styles;
