import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#fff5f0',
    paddingHorizontal: 20,
    paddingVertical: 50,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 20,
    zIndex: 10,
  },
  backBtn: {
    backgroundColor: 'white',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    height: 40,
    width: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageTitle: {
    fontSize: 20,
    fontFamily: 'Poppins-Bold',
    color: '#1a1a1a',
  },
  likeButton: {
    height: 40,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderColor: '#ffe3d9',
    borderWidth: 1,
    borderRadius: 20,
  },
  scrollViewStyle: {
    paddingBottom: 140,
    gap: 16,
  },
  card: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ffe3d9',
    elevation: 2,
    shadowColor: '#ff5b27',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
  },
  sectionTitle: {
    fontSize: 15,
    fontFamily: 'Poppins-Bold',
    color: '#1a1a1a',
  },
  addressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  addressName: {
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
    color: '#ff5b27',
    marginTop: 8,
  },
  addressText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    color: '#555',
    lineHeight: 18,
    marginTop: 4,
  },
  changeText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 13,
    color: '#ff5b27',
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 8,
  },
  divider: {
    height: 1,
    backgroundColor: '#ffe3d9',
    marginVertical: 12,
  },
  productImageContainer: {
    height: 52,
    width: 52,
    borderRadius: 8,
    backgroundColor: '#fff5f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  productImage: {
    width: '90%',
    height: '90%',
    borderRadius: 6,
    resizeMode: 'contain',
  },
  itemDetails: {
    flex: 1,
    marginLeft: 12,
    flexDirection: 'column',
  },
  itemName: {
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
    color: '#1a1a1a',
  },
  itemQty: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    color: '#777',
    marginTop: 2,
  },
  itemPrice: {
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
    color: '#1a1a1a',
    textAlign: 'right',
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 6,
  },
  priceLabel: {
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    color: '#666',
  },
  priceValue: {
    fontFamily: 'Poppins-Bold',
    fontSize: 13,
    color: '#1a1a1a',
  },
  freeText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 13,
    color: '#28a745',
  },
  totalText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 15,
    color: '#1a1a1a',
  },
  totalValueText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 17,
    color: '#ff5b27',
  },
  bottomBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 28,
    backgroundColor: '#fff',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderTopWidth: 1,
    borderColor: '#ffe3d9',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
  },
  totalLabel: {
    color: '#888',
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    marginBottom: -2,
  },
  totalAmount: {
    fontSize: 20,
    fontFamily: 'Poppins-Bold',
    color: '#1a1a1a',
  },
  payBtn: {
    backgroundColor: '#ff5b27',
    height: 48,
    borderRadius: 24,
    paddingHorizontal: 28,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#ff5b27',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
  },
  payText: {
    color: '#fff',
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
    marginBottom: -2,
  },
});

export default styles;
